### ISSUE TITLE
无法唤起ZIP

### ISSUE THREAD

**Issue by snowleung** [ShunCai/QZoneExport#13]
按下载后一直显示已下载
chrome
版本 74.0.3729.131（正式版本） （64 位）

总容量5.4G，已用2.4G，我F12调试的时候看到的。

**Comment by ShunCai** [comment]
自己多试几次看吧，暂时无法复现这个问题，2.4G最多会导致浏览器崩溃，或者稍等几天，下个新版本会支持浏览器和迅雷下载文件。

**Comment by mxy493** [comment]
同一直显示“已下载”，助手下载和浏览器下载都不行，试过多次了
<img width="601" alt="Snipaste_2020-03-12_14-15-57" src="https://user-images.githubusercontent.com/46776216/76493135-dc179500-646c-11ea-9333-ee39d1233566.png">

**Comment by Zlylanyun** [comment]
无法获取保存收藏内容



---原始邮件---
发件人: "mxy493"<notifications@github.com&gt;
发送时间: 2020年3月12日(周四) 下午2:22
收件人: "ShunCai/QZoneExport"<QZoneExport@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [ShunCai/QZoneExport] 无法唤起ZIP (#13)




 
同一直显示“已下载”，助手下载和浏览器下载都不行，试过多次了

**Comment by ShunCai** [comment]
会看控制台消息吗？F12。

![微信截图_20200312143916](https://user-images.githubusercontent.com/39191272/76494435-d40d2480-646f-11ea-9099-2498dcf67c0b.png)

**Comment by mxy493** [comment]
> 会看控制台消息吗？F12。
> 
> ![微信截图_20200312143916](https://user-images.githubusercontent.com/39191272/76494435-d40d2480-646f-11ea-9099-2498dcf67c0b.png)

刚准备复现一下，结果又可以了。就是这个1191张照片的相册，昨天试了四五遍都不行，每次都是一样的，照片数量小一点的相册没遇到过。但是这个相册1191张照片试了多次都是一样的情况。
后面如果再遇到同样的情况再来反馈~

**Comment by Zlylanyun** [comment]
视频下载不完



---原始邮件---
发件人: "mxy493"<notifications@github.com&gt;
发送时间: 2020年3月12日(周四) 下午3:56
收件人: "ShunCai/QZoneExport"<QZoneExport@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Zlylanyun"<www.1070260698@qq.com&gt;;
主题: Re: [ShunCai/QZoneExport] 无法唤起ZIP (#13)




  
会看控制台消息吗？F12。
 

  
刚准备复现一下，结果又可以了。就是这个1191张照片的相册，昨天试了四五遍都不行，每次都是一样的，照片数量小一点的相册没遇到过。但是这个相册1191张照片试了多次都是一样的情况。
 后面如果再遇到同样的情况再来反馈~
