### ISSUE TITLE
获取失败

### ISSUE THREAD

**Issue by Nasokin** [ShunCai/QZoneExport#14]
Chrome Version 79.0.3945.130 (Official Build) (64-bit)
只想导出说说，反复尝试了多次
1.0.2版本（还尝试了搜狗）：显示全0
1.0.3版本：获取0条，失败40条
另外导出相册也会有一部分迷之失败

**Comment by ShunCai** [comment]
重置一下配置项再试试。

**Comment by Nasokin** [comment]
原来就用的默认配置，重置之后也没有产生任何变化。
<img width="445" alt="Annotation 2020-01-30 221025" src="https://user-images.githubusercontent.com/25531203/73456766-6d471680-43ad-11ea-8521-9bc40e9a9681.png">

**Comment by ShunCai** [comment]
会看控制台和网络请求么，我这边试了几个QQ号都没问题。

**Comment by Nasokin** [comment]
实在抱歉不太会看……不知道是不是这个？
<img width="1080" alt="Untitled" src="https://user-images.githubusercontent.com/25531203/73458257-f5c6b680-43af-11ea-8577-46fbcce55002.png">

**Comment by Nasokin** [comment]
发现了如下的错误和警告，这就是所谓的接口问题吗
<img width="1080" alt="Untitled2" src="https://user-images.githubusercontent.com/25531203/73459141-47237580-43b1-11ea-848f-9657cce6c3c5.png">
<img width="1080" alt="Untitled" src="https://user-images.githubusercontent.com/25531203/73459143-47bc0c00-43b1-11ea-9d8d-61dedb330141.png">

**Comment by Nasokin** [comment]
结论：原来默认是每次获取40条，但我的神秘QQ获取40条就会出事，看到最新版改成20条了。如果哪位朋友还碰到类似的问题就去\js\config.js把跟说说相关的获取数量改成别的数字应该就没问题了。
