### ISSUE TITLE
正在下载完成后，如果没有点击打包下载，资料位置存储在哪里呢？

### ISSUE THREAD

**Issue by hbsun2113** [ShunCai/QZoneExport#21]
首先感谢作者！
我使用mac-chrome运行插件。
1. 我的插件可以成功执行“正在下载文件”，并且此时查看下载网速较大，说明此时已经开始下载文件到本地了。
2. 点击“打包下载”后，可以正常执行，但是观察到网速较慢，说明此时没有执行下载任务。并且，执行到100%后就卡住了，chrome默认的下载位置也没有相关文件。因此这个操作执行失败了。
3. 如果我不想使用“打包下载功能”，只想在“正在下载文件”结束后，直接到本地位置去找照片，请问应该去哪里找？

**Comment by ShunCai** [comment]
你的情况应该是文件过多，数据量过大，请在助手选项页调整下载工具为浏览器过迅雷x。

助手默认下载文件的工具是助手内部下载，该方式不适合数据量过大的。

助手内部方式的话，文件并没实际下载到磁盘，只是下载到浏览器，只有点击打包下载才会真正下载保存到磁盘。

**Comment by hbsun2113** [comment]
好的，感谢！
