### ISSUE TITLE
希望支持更多第三方下载工具

### ISSUE THREAD

**Issue by KaminoDice** [ShunCai/QZoneExport#22]
可能是相册文件太多了？
调用迅雷X下载老是崩溃
希望可以导出到aria2或者IDM下载

**Comment by ShunCai** [comment]
可以在选项页调整迅雷最大任务数，只是会导致多次唤起迅雷，且要人工操作确认任务比较麻烦。

或者调整下载方式为迅雷(下载链接)，这样打开迅雷且开启剪切板监听后，直接复制迅雷下载方式即可。

更推荐的方式为浏览器下载，有个用户几十个G也可以成功备份。

支持其它第三方工具的话，待定吧。

**Comment by ShunCai** [comment]
理论上，可以装个Aria2类的插件，拦截浏览器的下载请求并自动添加到Aria2，但没验证过。
不过，助手现已支持添加Aria2 RPC下载，但未发布新版本，可切换dev分支离线安装体验。
至于IDM的，不安排。
