### ISSUE TITLE
QQ空间手动浏览器下载图片（不通过QZoneExport），Chrome就自动覆盖前一个图片，这怎么回事?

### ISSUE THREAD

**Issue by jack91123** [ShunCai/QZoneExport#23]
装QZoneExport之前，Chrome从QQ空间手动下载图片，第一个命名为default.jpg，第二个自动命名为default(1).jpg。第三个default(2).jpg。类推。

装QZoneExport之后，如果Chrome从QQ空间手动下载图片（不通过QZoneExport），每一张图片都被内定为default.jpg，所以第二张就自动覆盖了第一张。也就是说如果下载10张不同图片，后面每张都自动覆盖前面的。最后只有1张default.jpg。

但是如果用QZoneExport下载就没有这种问题，所有10张图片都下载下来，而且名字都不同。

如果把QZoneExport暂时关闭，Chrome又立马回复正常。

这怎么回事？？？

下面的设置需要修改什么才能更正？

另外，第一次安装QZoneExport，记得下载后ZIP文件内部的文件夹是中文的，比如“说说”。后来我因为一些原因重装了一次QZoneExport，现在每次ZIP内部都是英文，比如“说说”变成了Diary等等。这怎么回事？

![Untitled2](https://user-images.githubusercontent.com/66239227/83380744-b4b9cf80-a3ac-11ea-8308-2711f089e5fd.png)
![Untitled](https://user-images.githubusercontent.com/66239227/83380746-b4b9cf80-a3ac-11ea-9012-90336a900311.png)

**Comment by ShunCai** [comment]
该问题是因为助手托管了下载管理，下载项重名时会自动覆盖文件，下个版本将会取消自动覆盖，改为询问或自动重命名。如果需要人工下载重名项，可临时禁用助手。

**Comment by jack91123** [comment]
谢谢这么快回复。还有第二个问题：

另外，第一次安装QZoneExport，记得下载后ZIP文件内部的文件夹是中文的，比如“说说”。后来我因为一些原因重装了一次QZoneExport，现在每次ZIP内部都是英文，比如“说说”变成了Diary等等。这怎么回事？

**Comment by ShunCai** [comment]
HTML和Markdown对英文的兼容较好，有些Markdown可能不支持中文的图片路径引用之类的，所以统一做了调整。
