### ISSUE TITLE
能否随时即开即用？

### ISSUE THREAD

**Issue by jack91123** [ShunCai/QZoneExport#24]
因为开启后，Chrome内置下载引擎会改为插件内置的覆盖性rule，遇到少图的空间，不想动用插件这么麻烦。本人喜欢关闭该插件，等有众多图片的QQ空间，再打开，下载完后立马又关闭。第一次即开即用没问题，可是第二次即开，就不能用了，点击插件显示的是插件选项，而不是下载的窗口。此时只有关闭Chrome，重新启动Chrome，再打开插件才能正常，不知作者大大有没有办法解决？

**Comment by ShunCai** [comment]
什么意思，没看懂。不知道是不是我理解问题，我试了下，没问题啊。
而且，助手只是支持调用Chrome下载器而已，实际上没有更换Chrome的下载引擎或下载管理页面，完全没必要停用呢。

**Comment by jack91123** [comment]
好像更新了一下插件，确实没有覆盖文件名的问题了，谢谢了。现在不用关闭了
