### ISSUE TITLE
下载的进度条到100%后卡住，没有生成下载的压缩包

### ISSUE THREAD

**Issue by bingsmocha** [ShunCai/QZoneExport#25]
![image](https://user-images.githubusercontent.com/18227727/86130846-5e5cbf80-bb17-11ea-9387-8710d46ca0f0.png)
如上图所示，不知道应该如何解决

**Comment by ShunCai** [comment]
建议把文件下载方式换下，换成浏览器过迅雷，光看页面也没法确实是不是ZIP包过大，但是一般都是。

**Comment by bingsmocha** [comment]
问题解决，多谢！
