### ISSUE TITLE
README 中所说的“不得用于商业用途” 与 Apache-2.0 License 冲突

### ISSUE THREAD

**Issue by ouuan** [ShunCai/QZoneExport#26]
任何开源软件（此处“开源软件”是一个专有名词，而非“开放源代码的软件”的缩写）都是允许商业使用的。在 Apache-2.0 License 中，明确授予了使用者以任何目的使用的权利，包括用于商业用途：

![许可证](https://user-images.githubusercontent.com/30581822/86236313-76424b00-bbcc-11ea-953f-a2f63f257bdc.png)

如果想要任何人在重新分发（例如做出一些修改后再进行发布）时保持开源，可以使用 GPL-3.0 License。

如果真的想杜绝商业使用，可以使用一个自定义协议（我不太清楚有没有什么现成的非开源协议）。

当然，个人认为杜绝商业使用是不必要的，只要别人遵守了 Apache-2.0 License，在重新发布时提到你这个项目，用户可以免费使用你这个项目而无需购买他人“倒卖”的软件，想要“倒卖”的人一般来说是卖不出去的。

**Comment by ShunCai** [comment]
没想到还会有人注意到这个，确实，开源协议我还是清楚的，但是怎么说呢，个人觉得：
1、怎么说呢，对于这种开源的工具的来说，开源协议没啥用，说的好听是爬虫，说得不好听是犯法，类似PanDownload被告的事情大有所在。
2、主要是项目一开始的时候，确实是Apache-2.0 License协议，至于为啥选，纯粹是比较喜欢MIT和Apache-2.0 License，然后A排前面。
3、然后后面怕有人倒卖，才在README加上个【注意】，并非强制要求，而且强制要求其实也没啥用，然后项目的协议也懒得改，而且，现在，遵从协议的很多，不遵从的也很多。
4、至于您说的没人倒卖，只能说，并非所有人都懂，懂得逛Github，懂得使用搜索引擎，懂得逛扩展商店，见过很多免费开源的软件工具，都有人在卖与买，最后逼得作者闭源了。

不管怎样，后面会把README的协议相关的东西移除，毕竟如你问题标题所言。

**Comment by ouuan** [comment]
确实是没几个人认真看协议，违反了也很难追究，但看到“禁止商用”和一个开源协议一起摆在那还是想提一下。

**Comment by ShunCai** [comment]
嗯，给你点个赞
