### ISSUE TITLE
无法唤醒迅雷，可以试试卸载重装

### ISSUE THREAD

**Issue by LioDon** [ShunCai/QZoneExport#27]
在使用较早版本的时候（估计是1.0.3吧），那时候我邮件和你沟通过，说是迅雷无法唤醒，当时我以为是插件的问题。当1.0.7更新之后，我发现这个问题依然存在。后来即便是换浏览器也无济于事。无奈，把迅雷卸载掉，然后在306管家里把和迅雷有关系的插件之类的东西也都挨个儿清理了一下，重新安装迅雷，这下迅雷可以正常唤醒了。具体是哪儿问题，我数不清，但希望能帮助到遇到同样问题的网友。
PS：由衷的感谢顺才兄在插件开发上的辛勤付出，并且还不断迭代。你就是广大QQ空间老用户的知音。向你致敬。

**Comment by ShunCai** [comment]
无法唤起迅雷的，一般是管家类应用禁用了迅雷的基础服务，可在优化项类取消禁用即可。
