### ISSUE TITLE
希望增加数据纠错功能

### ISSUE THREAD

**Issue by LioDon** [ShunCai/QZoneExport#28]
十年来，在空间里上发布了太多东西，而且还在不断增加中。光相册里的照片就多达16K+，说说近7K……但在备份插件的一番整理之后，最终给到的文件一共才12K+条，不管怎么说，都是有相当一部分数据是丢失的。而事实也确实如此。
我打开一个应该有31张照片的相册，实际下载下来的只有20张。其他的相册里，照片的数量没问题，但有些照片是损坏的，就是那种可以打开，但画面有破坏和缺失的那种。可对应的在Q空间的那张照片却没有问题，就算我点开看原图也是完好的。

所以，如果能够对本地数据和云端数据进行比对并进行纠错的话，这样的问题应该就不会存在了吧。

**Comment by LioDon** [comment]
对了，注意一下12074这个数，最后获取的总数就是这个数。几个月前用1.0.3版本的时候获取到的好像就是这个数，可这几个月来，我明明又在空间增添了新的内容，包括照片。
是哪个环节上设置了数量限制么？

**Comment by LioDon** [comment]
上边提到的12074是全部备份显示的数字。我尝试单独对相册备份，总数16K+的照片，最后给出的数字是15304。

**Comment by LioDon** [comment]
我对比了几个月前的那次备份，我发现同一张照片出现了不同的名字命名，具体表现为拥有同一个前缀，这个前缀是照片从相机那儿得到的文件名。紧接着有一个后缀，后缀看起来好像是个16进制的随机数，因为在同一个上它总是在变，这个变化就让不同时间备份的数据进行相互覆盖造成了不可能。就是说，如果所有数据不能一次性完成备份，想要通过二次备份进行数据修补就很困难。

**Comment by ShunCai** [comment]
数据纠错，只能人工，至于你说的数量不一致问题，我这边没遇到，也不好分析具体是什么问题。

**Comment by LioDon** [comment]
对了，我用插件对空间进行备份的过程中注意到这样一个问题，就是在尝试备份几次之后，相册里的相册不显示了，换浏览器也没用，但这时候在手机客户端上看相册也还在，也能点击去浏览，唯独网页版的不行。等个一阵子，大概十几分钟之后，重新在网页上登录空间，就又恢复正常，相册也可以正常查看了。所以，腾讯官方是不是有什么保护机制？是不是这个所谓的保护机制影响到了最终的数量获取？昨天白天我又多次尝试备份，全量备份全空间的那种，但最后获得数量比前天还少，只有区区3K+了。所以再次回到那个问题，是不是短时间的大量访问触发了保护机制然后影响到了最终费数据获取？

**Comment by ShunCai** [comment]
有的，所以，可以选项页调整数据获取间隔。

**Comment by LioDon** [comment]
那么，这个间隔该怎么调？可否给个指导？

**Comment by LioDon** [comment]
那么，这个间隔该怎么调？可否给个指导？

**Comment by ShunCai** [comment]
选项页调，每个模块有个间隔调整。

**Comment by LioDon** [comment]
那个我看见了，关键是两个数字要分别怎么调整？对应什么含义？调整过程中有什么注意事项？遵循什么原则？

**Comment by ShunCai** [comment]
左边是最小，右边是最大。
假如左边是2，右边是5，那每次请求下一页数据的时候，就会随机等待2到5秒再请求。

**Comment by LioDon** [comment]
原来是这么个意思，了解了。那如此说来是设置的时间越长就越容易躲过系统检测呗？
对了，考虑到单次全量备份所有数据会出现因为连续访问次数过多而被系统屏蔽，能否设法单次只备份一部分，待所有数据都下载到本地后再进行汇总？这样成功率是不是会提高？

**Comment by ShunCai** [comment]
本来就支持，可单个模块备份，可单个相册备份，可增量备份。

简单来说，把所有模块增量备份开启，然后先备份说说，此时会下载说说的配图文件，下完后备份完后，不需要打包下载，然后再备份日志，此时会下载日志的配图文件，下载完成后，点击打包下载，解压合并配图文件下载文件夹，然后就会同时有说说跟日志的内容。

其它的同理。相册的可单个备份，开启增量备份后，第一次备份a相册，第二次备份a和b或只备份b，最终导出的数据同时存在a和b相册数据。

**Comment by LioDon** [comment]
原来如此，这要是不细问还真不知道可以这样操作。也不知道是不是还有其他的隐藏技能。如果可以的话，出一个针对性的图文教程把这些小技巧汇总一下，那就方便多了。

**Comment by ShunCai** [comment]
我觉得功能很明显啊。。。

**Comment by LioDon** [comment]
关键是你是程序员嘛，自己的设计当然了解。但对于像我这样的非程序员用户，想要直观的了解程序所包含的功能以及怎么最大化发挥他的威力等方面，还是不如你了解的更加透彻。其实大多数的用户是非程序员用户，对于你挖空心思设计一些奇巧功能的理解肯定没你深入，遇到一些小问题也不知道该怎么排查的时候，可能有些人会觉得这个插件设计得比较复杂，不好调整；有些人会觉得这个插件还不够强，所以会出现各种问题…等等诸如此类比较影响使用体验的想法。但实际上是多数人看不透，甚至根本就不知道腾讯官方对数据访问还存在保护机制这样的问题。所以说，一个较为详尽的使用说明也算的上是对程序本身的完善。
