### ISSUE TITLE
插件没办法加载

### ISSUE THREAD

**Issue by lzhaoyang** [ShunCai/QZoneExport#3]
谢谢repo主写的插件，但是我在使用过程中出现了问题，我的chrome版本是：
![微信截图_20190614091033](https://user-images.githubusercontent.com/14249262/59476866-46bb8600-8e85-11e9-997b-cc7680955b6d.png)
出现的问题是：
![微信截图_20190614090835](https://user-images.githubusercontent.com/14249262/59476877-4fac5780-8e85-11e9-89ad-c59c01acc00e.png)
不知道是不是bug还是啥，希望能够优化一下。再次感谢您做的这个工具

**Comment by lzyroot** [comment]
同样有这个问题

**Comment by lzhaoyang** [comment]
> 同样有这个问题
提示说没法加载vendor下的StreamServer文件夹下的js，应该是repo主没有提交上来感觉，我尝试在vendor下创建对应的文件夹和空的js  是可以安装上的，就是不知道影不影响空间备份的基本功能就是

**Comment by HelloJquery** [comment]
同这个问题，上个版本是可以用的

**Comment by lzyroot** [comment]
放弃用这个了，其实QQ空间APP就可以下载，还能下载之前上传的原图，每次限制50张，不过可以突破限制

**Comment by ShunCai** [comment]
我是随便提了下代码，没想到会有人用，所以没留意。
