### ISSUE TITLE
相册导出失败

### ISSUE THREAD

**Issue by Downtime111** [ShunCai/QZoneExport#30]
获取相册列表失败，下载也下不了，这是什么问题呢
![TIM截图20200728135245](https://user-images.githubusercontent.com/44515289/88624493-aac8fa00-d0d9-11ea-9bfd-9f9be6956556.png)

**Comment by ShunCai** [comment]
光看这个没办法知道问题

**Comment by ShunCai** [comment]
1、试下重新安装后是否可以，如果在线安装或crx安装还是不行，可以试试zip的离线安装。
2、导出他人空间还是导出自己空间，如果是他人空间，确认是否有权限。
3、用的是浏览器？Chrome、360、Edge或者其它。
4、如果以上都没问题，你会不会看浏览器控制台，F12->Console，看看有没有报错，如果有，截个图。

因为涉及隐私问题，所以助手没有做相关的日志收集功能，所以不好分析问题。

**Comment by dangehub** [comment]
我来说下我遇见的问题吧，第一次成功获取了所有照片的信息，但是全部下载失败，第二次尝试就如lz这样了，这时候返回相册发现相册是一片空白，我怀疑是因为之前一直在读取所以被tx限制了。

**Comment by ShunCai** [comment]
第二次重试的时候，有重新刷新页面吗？
助手目前不支持不刷新页面的时候重复备份。

如果只是收集到数据但是文件下载失败的话，
建议更换文件下载工具，不使用助手内部，如果更换了下载工具还不行的话，建议重装一次。
如果重装还不行的话，再说吧(╯﹏╰)b
![image](https://user-images.githubusercontent.com/39191272/105118976-5a6fa980-5b0a-11eb-99dc-e0eeeb5953bc.png)


就这种程度的读取，一般不会限制。
如果限制，可以在配置也调整数据获取的间隔时间。
