### ISSUE TITLE
图片文件导出出错

### ISSUE THREAD

**Issue by HayashiRyu** [ShunCai/QZoneExport#34]
最后一步显示下载文件全部失败，打开压缩包后发现相册文件夹为空。

![001](https://user-images.githubusercontent.com/61179776/91781751-adb19000-ec2d-11ea-9121-29f28a9b2ccd.png)
![002](https://user-images.githubusercontent.com/61179776/91781754-aee2bd00-ec2d-11ea-875f-6d10d2031001.png)
![003](https://user-images.githubusercontent.com/61179776/91781757-b013ea00-ec2d-11ea-8f22-1199e4820192.png)
![004](https://user-images.githubusercontent.com/61179776/91781759-b2764400-ec2d-11ea-94de-4a79849c3f18.png)

**Comment by ShunCai** [comment]
最近没空，晚点抽空看看，你可以先在助手配置页把文件下载方式换成浏览器下载试试。

**Comment by ShunCai** [comment]
如果使用助手内部下载的话，可右键点击扩展图标看看如下配置：
![image](https://user-images.githubusercontent.com/39191272/92301422-6fea9980-ef96-11ea-87e3-f1204b64ff77.png)

话说，其实不建议使用助手内部下载文件，优先适用浏览器下载吧。如果浏览器下载有问题的话，可确认图片地址是否能正常打卡。

**Comment by HayashiRyu** [comment]
改成浏览器下载后确实下载了很多文件，但压缩包里面Albums文件夹里还是没有图片。

**Comment by ShunCai** [comment]
浏览器下载和迅雷下载压缩包里本来就是没文件，需要到相应的下载目录人工拷贝与解压目录覆盖合并。

**Comment by HayashiRyu** [comment]
好了，已解决

**Comment by ShunCai** [comment]
备份时没选相册？
