### ISSUE TITLE
请问是否可以修改获取数据的时间？

### ISSUE THREAD

**Issue by lotustalk** [ShunCai/QZoneExport#4]
尝试过两次，因为获取日志的速度太快总是失败而且会让登录qq被冻结，可能因为企鹅认为是在发广告之类的吧，所以想问下是否有设置获取日志的间隔，比如说间隔10s20s之类，或者可以设置获取日志的时间范围比如2018-2019这样。。。谢谢大佬的代码

**Comment by ShunCai** [comment]
是的，太快会被冻结，但就目前来说，只有说说列表和相册列表太快会被冻结，没遇到过日志列表冻结的情况，目前基本都有默认间隔，后面会有时间间隔的配置项，只是一直忙没加。
