### ISSUE TITLE
获取说说图片时出错

### ISSUE THREAD

**Issue by xsy2004** [ShunCai/QZoneExport#40]
报错信息如下
[![0JiIQf.png](https://s1.ax1x.com/2020/10/04/0JiIQf.png)](https://imgchr.com/i/0JiIQf)
盲猜是因为请求头的问题，和跨域的问题。

**Comment by xsy2004** [comment]
这个同样可以在单独备份相册的时候复现，通过进入下载管理然后全选，点击浏览器下载可以解决。

**Comment by ShunCai** [comment]
通过助手内部ajax请求下载坑就是多，跨域，https之类的问题一堆，不过印象中当初是测试过没跨域问题的，很久没用助手内部下载了，不知道是不是什么时候改出问题了，待会试试看，我都很久没用助手内部下载了，我一般都用浏览器下载，后续打算把这个干掉不要了。

**Comment by xsy2004** [comment]
> 通过助手内部ajax请求下载坑就是多，跨域，https之类的问题一堆，不过印象中当初是测试过没跨域问题的，很久没用助手内部下载了，不知道是不是什么时候改出问题了，待会试试看，我都很久没用助手内部下载了，我一般都用浏览器下载，后续打算把这个干掉不要了。

也就是把公共的下载改成浏览器下载就成了咯

**Comment by ShunCai** [comment]
对的，建议使用浏览器、迅雷或Aria2下载。助手内部下载的话，图片文件太多也没法正常打包下载。

**Comment by xsy2004** [comment]
又碰到了问题，浏览器下载的文件无后缀，所以识别不了文件
![0JQbvQ.png](https://s1.ax1x.com/2020/10/04/0JQbvQ.png)
手动修改就可以了，并且从index.html访问备份说说的时候报错。
![0Jlkr9.png](https://s1.ax1x.com/2020/10/04/0Jlkr9.png)
就是个含有报错信息的文件，其他啥都没

**Comment by ShunCai** [comment]
除了相册会生成后缀名，其他的备份图片默认没有生成文件名后缀。可以在选项公共模块打开文件名后缀识别，但是个人觉得没必要，还费时。
首页报错的话，是用了最新版本么，打开首页给报错信息我看看，初步怀疑是新版加的东西导致的。

**Comment by ShunCai** [comment]
如果没有打开文件名后缀识别，不建议人工修改文件名的后缀，不然打开HTML会看不到图片。

**Comment by xsy2004** [comment]
> 除了相册会生成后缀名，其他的备份图片默认没有生成文件名后缀。可以在选项公共模块打开文件名后缀识别，但是个人觉得没必要，还费时。
> 
> 首页报错的话，是用了最新版本么，打开首页给报错信息我看看，初步怀疑是新版加的东西导致的。

是空间还是生成的文件报错，如果是文件的话这个就是源代码，就这一行字，是最新版本1.0.9

**Comment by ShunCai** [comment]
不用了，我知道了。是新增的最近访问功能导致的，忘了兼容最近访问没开启的情况了。
解决方法是，把说说、日志、相册的最近访问功能打开，然后重新备份。
![image](https://user-images.githubusercontent.com/39191272/95018683-dba64c00-0693-11eb-8ed5-59b9d7be5f92.png)

**Comment by xsy2004** [comment]
> 不用了，我知道了。是新增的最近访问功能导致的，忘了兼容最近访问没开启的情况了。
> 解决方法是，把说说、日志、相册的最近访问功能打开，然后重新备份。
> ![image](https://user-images.githubusercontent.com/39191272/95018683-dba64c00-0693-11eb-8ed5-59b9d7be5f92.png)

谢谢
