### ISSUE TITLE
相册备份全部失败，照片全部丢失

### ISSUE THREAD

**Issue by zhangcheele** [ShunCai/QZoneExport#43]
一万张照片
点了备份，结果全部丢失了
怎么找回来啊

**Comment by ShunCai** [comment]
丢失？什么意思？
打开增量备份的情况下，重新备份了？
备份完了之后，打开相册HTML没显示相册。
还是说打开相册HTML图片显示不出来？

如果是只是无法正常显示相册的话，应该是新增的备份最近访问功能导致的。

临时解决方案：
如果是全量备份的话，需要打开最近访问的功能再备份。
如果是增量备份的话，然后无法显示相册的话，需要重新备份，或者晚点会我发个版本你再增量备份。

**Comment by 215570531** [comment]
备份完解压之后的相册HTML图片显示不出来，返回空间相册网页页面相册都不见了？怎么操作呀

**Comment by ShunCai** [comment]
助手不会导致空间相册网页页面相册丢失。

如果是备份完解压之后的相册 HTML 图片显示不出来的问题，更新助手重新备份即可，问题已在新版本修复。
