### ISSUE TITLE
下载的图片没有原始的创建时间

### ISSUE THREAD

**Issue by w4lle** [ShunCai/QZoneExport#44]
RT.

**Comment by ShunCai** [comment]
文件创建时间与照片拍摄时间是不相同的。
文件创建时间目前没有办法指定，哪怕去QQ空间官方下载，文件夹的创建时间也是你下载的时间，只有相片的Exif信息视你上传相片时，是否勾选原图。

至于照片的拍摄时间（仅适用相册含有原图的照片，即上传照片时勾选原图，非高清原图），根据下载工具的不同而不同：
1、使用助手内部下载的，相片不含Exif信息，也就是拍摄时间、拍摄设备、拍摄地点等。
2、使用Aria2、浏览器、迅雷下载时，相片含Exif信息，也就是拍摄时间、拍摄设备、拍摄地点等。

至于如何查看相片的Exif信息，以下仅适用Windows系统：
![image](https://user-images.githubusercontent.com/39191272/96561261-e7c81580-12f1-11eb-9047-4a28b3442cff.png)
