### ISSUE TITLE
当相册数据较大时（6000张），下载失败

### ISSUE THREAD

**Issue by w4lle** [ShunCai/QZoneExport#45]
![image](https://user-images.githubusercontent.com/7310246/96562104-f662fc80-12f2-11eb-9d23-e14bfcf1fa15.png)

看起来是视频过期了？
怎么规避这个问题

**Comment by ShunCai** [comment]
这个暂时还没办法解决，详细请看#41

**Comment by w4lle** [comment]
如果限制每次下载100个，是可以的，会不会是获取相片详情耗时太久导致的（6000个，大概需要10分钟）

**Comment by ShunCai** [comment]
应该不是耗时的问题，有可能是并发的问题，我抽空再看看。

**Comment by w4lle** [comment]
你的意思是并发请求相片详情接口太多，会返回vwecam.gtimg.com开头的下载地址吗？

**Comment by w4lle** [comment]
我抓包看下

**Comment by ShunCai** [comment]
> 你的意思是并发请求相片详情接口太多，会返回 vwecam.gtimg.com 开头的下载地址吗？

不是，下载地址跟并发没关系，QQ空间之前一直用的都是类似vwecam.gtimg.com的视频地址，自从更换photovideo.photo.qq.com地址后，之前的地址就经常这样下载失败了，还没研究，目前还不知道什么问题。

现在新上传的视频，目前好像都是用了photovideo.photo.qq.com的服务器，类似vwecam.gtimg.com的，都是未更换前的地址了。

**Comment by w4lle** [comment]
确实是这样的，最近的视频是photovideo.photo.qq.com，更早之前的视频地址是vwecam.gtimg.com。
如果不勾选视频，还会去下载视频吗？先把照片备份出来

**Comment by ShunCai** [comment]
不勾选视频，也会下载视频，会下载相册里面的视频。视频模块的是否勾选，决定的是视频QQ空间相册模块的视频模块的视频是否下载，但是理论上来说，QQ空间视频模块的视频，都会在相册里有体现的。

但是，现在的逻辑，视频的下载失败，不影响相册的备份。

**Comment by w4lle** [comment]
get
另外，下载的文件，createTime&modifyTime时间是now，能不能修改为shoottime，exif中没写入的话原始拍摄时间信息就会丢失

**Comment by w4lle** [comment]
当然这个需要调用Native方法，因为是存放在本地文件系统，不知道能否实现

**Comment by ShunCai** [comment]
这个不行，助手说白了就是个JS应用，玩不来。

**Comment by ShunCai** [comment]
视频下载的问题，已经找出原因了，是QQ空间开启了Referer防盗链验证。

目前只有Aria2和迅雷下载有解决方案并且仅在dev分支修复。

浏览器下载目前没有找到好的解决方案，Chrome扩展提供的API都不允许更改Referer，
有个方案太麻烦，先使用xhr下载，再转blob，再调用Chrome的下载。

如果着急备份，可以源码安装dev分支备份，然后使用Aria2或迅雷X下载。
