### ISSUE TITLE
情侣空间

### ISSUE THREAD

**Issue by weinierfei** [ShunCai/QZoneExport#46]
当年有个情侣空间,那里头有一段记忆,楼主能找回来么

**Comment by ShunCai** [comment]
这就很尴尬了，楼主是单身dog，没有开通过情侣空间，现在PC端也找不到情侣空间的入口，手机端好像倒是有一个，但是不知道行不行。

**Comment by ShunCai** [comment]
而且，现在手机端的情侣空间跟一开始的那个情侣空间好像不是同一个情侣空间，
也不知道新版情侣空间跟旧版情侣空间是不是分开的，旧版情侣空间的数据有没有迁移到新版情侣空间。

如果是分开的，旧版我没开通过，所以研究入口都找不着。
新版的话，有时间我看看。

**Comment by hidetag** [comment]
手机的情侣空间是个 QQ 小程序；
实际上情侣空间里的相册在 QQ 空间里是同步的，只不过是私密相册，你上传图片到情侣空间的相册里，实际上是上传到 QQ 空间的相册

**Comment by ShunCai** [comment]
那看来你也没用过旧版的情侣空间，旧版情侣空间不是个小程序。

如果是同步的话，那你直接备份QQ空间的相册不就OK了么。

**Comment by weinierfei** [comment]
以前开通过,现在入口都没有了,找不到了

**Comment by ShunCai** [comment]
> 以前开通过,现在入口都没有了,找不到了

那现在是不是会同步到QQ空间相册嘛。如果会的话，直接备份QQ空间相册不就OK了么

**Comment by weinierfei** [comment]
> > 以前开通过,现在入口都没有了,找不到了
> 
> 那现在是不是会同步到QQ空间相册嘛。如果会的话，直接备份QQ空间相册不就OK了么

哈哈,这个并没有

**Comment by ShunCai** [comment]
暂时没办法，如果要做的话，也只能手机端上想办法，PC端连入口都没了，而且QQ小程序的认证方式不一样。
哪位大神有方法的话可以分享下。
