### ISSUE TITLE
下载文件失败 

### ISSUE THREAD

**Issue by CuntBoy** [ShunCai/QZoneExport#48]
![A`D1S_IS Z(B 706S_W4 9P](https://user-images.githubusercontent.com/30249564/98799569-3f1d5980-244a-11eb-9c8e-522417cb1fc0.png)
网络什么的都是没有问题的

**Comment by ShunCai** [comment]
方案一：
点击下载管理按钮，选择失败的图片，点击预览，浏览器提示不安全，界面上找到继续前往或信任证书之类的点击。

方案二：助手选项页，公共模块修改文件下载工具为浏览器或其他。

**Comment by CuntBoy** [comment]
好的  我尝试下
