### ISSUE TITLE
能否支持空间分享导出？

### ISSUE THREAD

**Issue by grdaimap** [ShunCai/QZoneExport#49]
有很多分享到QQ空间的链接，占了动态很大一部分，不能备份很可惜(´。＿。｀)

**Comment by grdaimap** [comment]
![image](https://user-images.githubusercontent.com/36882078/99138717-90596300-266d-11eb-9227-fe5a9a2c5700.png)
比如这种分享链接

**Comment by ShunCai** [comment]
怎么又一个想备份分享的，分享模块有点麻烦了，而且感觉不是很重要，所以当初没支持，我抽空看看吧。
