### ISSUE TITLE
当相片获取量到达一定数目时(4k+)下载备份会出现网页崩溃异常。

### ISSUE THREAD

**Issue by LunaticTian** [ShunCai/QZoneExport#5]
插件版本：1.0.1
chrome版本：78.0.3904.108

复现方法：获取完毕相册时(相片数量4K+)点击下载，在未来的10分钟内必现网页奔溃的现象。暂无解决办法..

**Comment by LunaticTian** [comment]
目前解决方案是先删除部分相册进行下载，然后替换回收站的相册再次进行下载。

**Comment by ShunCai** [comment]
> 目前解决方案是先删除部分相册进行下载，然后替换回收站的相册再次进行下载。



> 插件版本：1.0.1
> chrome 版本：78.0.3904.108
> 
> 复现方法：获取完毕相册时 (相片数量 4K+) 点击下载，在未来的 10 分钟内必现网页奔溃的现象。暂无解决办法..

目前超过总大小达到4G无法下载，后面有时间会优化下，如果无法解决超4G大小的问题，会考虑分批下载，或单个相册下载。

**Comment by LunaticTian** [comment]
感谢~
