### ISSUE TITLE
相册图片全部下载失败，试了好多次了（其他的下载都是正常的）

### ISSUE THREAD

**Issue by jinhong-wu** [ShunCai/QZoneExport#50]

**Comment by ShunCai** [comment]
现在使用什么下载工具。如果是助手内部的话，建议换成浏览器

**Comment by jinhong-wu** [comment]
谷歌浏览器，卸载重新安装好几次了，都是相册图片全部下载失败

**Comment by ShunCai** [comment]
看下助手的配置
![image](https://user-images.githubusercontent.com/39191272/101426818-ad194b80-3938-11eb-90d0-69bf5faf9234.png)

**Comment by jinhong-wu** [comment]
图片我看不到

**Comment by jinhong-wu** [comment]
![image](https://user-images.githubusercontent.com/33945675/101427312-98898300-3939-11eb-9846-78287753cd0f.png)

**Comment by ShunCai** [comment]
公共->文件下载->文件下载工具

**Comment by jinhong-wu** [comment]
哇撒！成功了！非常感谢！
