### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by nikolaeasy** [ShunCai/QZoneExport#51]
请问html文件用哪个浏览器打开好一点？感觉显示都有一些问题，IE显示问题比较大，Chrome和Edge打开稍微正常一些，但即使是用Edge说说的照片和相册的照片之类的也显示不出来

IE
![image](https://user-images.githubusercontent.com/45062613/102326296-3545c380-3fbf-11eb-9563-1a2bd48c12bb.png)

Microsoft Edge
![image](https://user-images.githubusercontent.com/45062613/102326168-062f5200-3fbf-11eb-9686-7f1021800604.png)
![image](https://user-images.githubusercontent.com/45062613/102326406-53132880-3fbf-11eb-9bf0-ed0b05675a07.png)
![image](https://user-images.githubusercontent.com/45062613/102326547-7f2ea980-3fbf-11eb-81f4-cc6b56295f8f.png)

**Comment by ShunCai** [comment]
只要是现代浏览器都没啥问题，比如Chrome，360，新版Edge、百分、UC等等，但是IE未测试过也不推荐。

图片不显示的，请确认图片是否正常下载。如果正常下载了，请确认ZIP包解压文件夹和下载图片的文件夹已合并。

比如，如果你使用迅雷下载图片与视频，进入到迅雷下载目录，然后把【QQ空间备份】文件夹拷贝到ZIP包解压之后的【QQ空间备份】文件夹进行合并，如果使用浏览器、Aria2下载图片与视频，参考迅雷方式，进入到相应的下载目录拷贝文件夹进行合并。

至于视频页面显示template.js error，可以在浏览器页面按F12，然后如图截图给我。
![](https://i.loli.net/2020/12/16/5j2tzX4ZNOUy1gF.png)
