### ISSUE TITLE
需要“查看全文”的长说说会丢失回车符

### ISSUE THREAD

**Issue by Tsubamei** [ShunCai/QZoneExport#66]
点开“查看全文”后，原来好几行的说说会变成一整段

**Comment by ShunCai** [comment]
已修复，暂无版本发布计划，动手能力强的话，可以切换dev分支采用源码安装方式，不然就等下次发布版本吧。

[![4eUzKs.png](https://z3.ax1x.com/2021/09/16/4eUzKs.png)](https://imgtu.com/i/4eUzKs)
