### ISSUE TITLE
希望增加“查看全文”说说全部展开的选项

### ISSUE THREAD

**Issue by Tsubamei** [ShunCai/QZoneExport#67]
不手动点击“查看全文”展开的说说，在网页中Ctrl+F会搜索不到对应内容

**Comment by ShunCai** [comment]
已优化，暂无版本发布计划，动手能力强的话，可以切换 dev 分支采用源码安装方式，不然就等下次发布版本吧。

[![4eaCV0.png](https://z3.ax1x.com/2021/09/16/4eaCV0.png)](https://imgtu.com/i/4eaCV0)
