### ISSUE TITLE
建议把导出的内容，生成为html；md格式查看的话不太方便。

### ISSUE THREAD

**Issue by MrBenWang** [ShunCai/QZoneExport#7]
另外，我也分享一下去年写的 python导出qq空间内容的脚本。😁😁😁

https://github.com/MrBenWang/MyBackUp/blob/master/python/20190101-get-qzone-liuyan.py
https://github.com/MrBenWang/MyBackUp/blob/master/python/20181230-get-qzone-shuoshuo.py
https://github.com/MrBenWang/MyBackUp/blob/master/python/20190718-get-qzone-photos.py

**Comment by ShunCai** [comment]
> 另外，我也分享一下去年写的 python 导出 qq 空间内容的脚本。😁😁😁
> 
> https://github.com/MrBenWang/MyBackUp/blob/master/python/20190101-get-qzone-liuyan.py
> https://github.com/MrBenWang/MyBackUp/blob/master/python/20181230-get-qzone-shuoshuo.py
> https://github.com/MrBenWang/MyBackUp/blob/master/python/20190718-get-qzone-photos.py

个人不太喜欢HTML，python版的我之前也准备写个，因为Chrome扩展受限太多了，只是一直忙得很没写。之前看到一个python版的导出，也是所有内容都导出了的，好像就是以HTML形式导出的。而且你有Python版，就没必要用Chrome版了，我的版本还有很多问题，例如说说和日志的评论超好像不能全部导出等等，毕竟当初只是写来自己用的。😁😁😁

**Comment by MrBenWang** [comment]
非常好奇的问一下，为什么不喜欢html吗？我个人是认为，目前html唯一可以`统一所有界面`的东西。

确实，我发现Chrome下载速度很慢，好像还是在博主的网站上下载的；虽然有些缺陷，但非常非常便于大家使用。
还想说一点就是，qq空间的机器审核越来越严厉，导致好多很久以前发布的内容都404了，非常非常郁闷。

**Comment by ShunCai** [comment]
> 非常好奇的问一下，为什么不喜欢html吗？我个人是认为，目前html唯一可以`统一所有界面`的东西。
> 
> 确实，我发现Chrome下载速度很慢，好像还是在博主的网站上下载的；虽然有些缺陷，但非常非常便于大家使用。
> 还想说一点就是，qq空间的机器审核越来越严厉，导致好多很久以前发布的内容都404了，非常非常郁闷。导出微博，导出微信朋友圈；尤其是导出朋友圈，这个还是蛮难的，我目前也是用第三方的平台功能，post抓取的。不知道博主有什么想法没有。
朋友圈的抓取，之前了解过一点，朋友圈的抓取很麻烦，协议不一样，一般都是用第三方的平台抓，例如微信书之类的，又或者通过python抓，又或者在在安卓手机抓，但是这些一般都是模拟人看朋友圈的过程，第三方平台基本都是这么干的。

**Comment by zhaofeng-shu33** [comment]
chrome 抓取的是 html 页面，怎么转成 md 的？

**Comment by ShunCai** [comment]
助手除了日志和私密日记外，其他抓取的是数据，MD是基于数据生成的。日志的抓取的是HTML，目前用了第三方库左转换，原来是通过HTML标签转换成MD语法。
