### ISSUE TITLE
建议在相册浏览界面增加图片时间和大小信息

### ISSUE THREAD

**Issue by Tsubamei** [ShunCai/QZoneExport#70]
![Snipaste_2021-11-10_16-33-19 拷贝](https://user-images.githubusercontent.com/61179776/141078813-759da958-f7bf-43b5-a57b-e6eb00b4909f.png)
如图

**Comment by ShunCai** [comment]
很有想法嘛，不过你这不是已经改了么，直接把代码改了得了。

而且，光棍节，你这图是很有节日气氛。

**Comment by ShunCai** [comment]
今天研究了一下，不太好搞，毕竟备份出来的HTML是纯静态页面，受限太多，很多东西压根用不了。

QQ空间本身的相片不含Exif信息，只带了上传的时间和错误的大小信息，没有相片的拍摄时间和原图的大小。

所以无法取到Exif信息，要额外调用QQ空间的接口取Exif信息，这又会增加备份时长。

如果只是备份时长增多好说，可是取出来的Exif压根就不对，不是原图的Exif信息，比如，相片的的大小和分辨率，明明原图是几MB的大小，取到的结果却是几百KB。

可能只能把上传时间和错误的大小，还是相片类型显示一下。

**Comment by Tsubamei** [comment]
其实图片是P的，只是示意一下
我觉得用QQ空间自带的上传时间和大小信息就可以，不用搞的太复杂。毕竟很多图片传上去就压缩了，也不含什么exif信息

**Comment by ShunCai** [comment]
行，只是显示上传时间和大小信息的话，那感觉意义不大，原图还是有Exif信息的。
