### ISSUE TITLE
备份时下载工具选项被重置到浏览器下载

### ISSUE THREAD

**Issue by szl0834** [ShunCai/QZoneExport#72]
EDGE 96.0.1054.57 版本
插件版本最新

当备份项目数量达到四五千的时候，原本设置的下载工具aria就会被重置到浏览器下载。
备份项目数量2000以下是运行正常的。
但是关于到多少数量会触发这个bug没有做太多测试，比较跑一次上千数量的备份太费时间了

**Comment by ShunCai** [comment]
我检查了和验证了一下，应该不会存在改问题。

因为备份过程中是不涉及改下载工具的，只有在配置页面才会更新配置。

而且我自身上万以及很多人都超3000千的，也没收到过类似的反馈。

你是不是曾经重置过配置项？如果不是的话，我只能再持续关注一下。

**Comment by szl0834** [comment]
> 我检查了和验证了一下，应该不会存在该问题。
> 
> 
> 
> 因为备份过程中是不涉及改下载工具的，只有在配置页面才会更新配置。
> 
> 
> 
> 而且我自身上万以及很多人都超3000千的，也没收到过类似的反馈。
> 
> 
> 
> 你是不是曾经重置过配置项或者改了配置没保存？如果不是的话，我只能再持续关注一下。
我重新从edge商店安装了一遍插件又恢复正常了，之前是chrome商店装的，不知道是什么原因引起的。
不过现在用起来没啥问题，感谢作者🙏。

**Comment by ShunCai** [comment]
好的，不客气
