### ISSUE TITLE
软件没法运行啊？

### ISSUE THREAD

**Issue by cqzaiercn** [ShunCai/QZoneExport#73]
软件没法运行啊？
![image](https://user-images.githubusercontent.com/37819946/147681023-48aed549-72a0-437f-99cd-0983c2bb4951.png)

**Comment by ShunCai** [comment]
看[Readme](https://github.com/ShunCai/QZoneExport/blob/master/README.md)和[Wiki](https://github.com/ShunCai/QZoneExport/wiki/Help)

**Comment by bGZo** [comment]
用白号登录试了下可以用, 之后我再切回主号也可以了. 😂

(ps 可能空间有啥设置不对也懒得改了.
