### ISSUE TITLE
迅雷下载没有Exif，也没有拍摄时间

### ISSUE THREAD

**Issue by cqboyone** [ShunCai/QZoneExport#75]
迅雷下载Exif是下载时间，也没有拍摄时间。
![image](https://user-images.githubusercontent.com/31926210/151185929-38f10beb-454a-45d4-ade2-59b7a71036c2.png)
![image](https://user-images.githubusercontent.com/31926210/151185967-63dae6fc-14a4-4235-9848-3bae0720cc5e.png)

**Comment by ShunCai** [comment]
刚刚试了一下，有Exif信息啊，是不是你图片本身在QQ空间就没Exif信息或不是原图？

![image](https://user-images.githubusercontent.com/39191272/151193564-b7251874-f40e-47b5-a966-160eaff168f6.png)

**Comment by cqboyone** [comment]
> 刚刚试了一下，有Exif信息啊，是不是你图片本身在QQ空间就没Exif信息或不是原图？
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/39191272/151193564-b7251874-f40e-47b5-a966-160eaff168f6.png)
> 
> 
那应该是没有的。话说大佬有打算对没有Exif的照片插入拍摄时间修改创建时间吗？我看json里面有记录时间。

**Comment by cqboyone** [comment]
还有视频也能判断下有没有Exif，没有就加上或者直接重置Exif吗？不知道为啥，家人qq空间下载下来的照片和视频都没有exif。

**Comment by ShunCai** [comment]
> > 刚刚试了一下，有Exif信息啊，是不是你图片本身在QQ空间就没Exif信息或不是原图？
> > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/39191272/151193564-b7251874-f40e-47b5-a966-160eaff168f6.png)
> > 
> > 
> 那应该是没有的。话说大佬有打算对没有Exif的照片插入拍摄时间修改创建时间吗？我看json里面有记录时间。
> 

修改创建肯定是没戏，因为创建时间就是图片下载的生成时间，纯js肯定是没法搞的。只能下载后自己用第三软件改。

回写exif的话，好像有方案，但是贼麻烦，而且还涉及用浏览器生成大文件压缩包文件内存崩的问题。

最重要的一点是，没有exif信息怎么回写，json里面的时间，不是拍摄时间，是上传时间。

**Comment by ShunCai** [comment]
> 还有视频也能判断下有没有Exif，没有就加上或者直接重置Exif吗？不知道为啥，家人qq空间下载下来的照片和视频都没有exif。

那估计上传的时候没传原图，或者说抹掉exif信息后再上传的。

自己去QQ空间下载一下就知道有没有exif信息了，如果QQ空间下载都没有，我能怎么办，还能凭空生成不成？

助手说白了，只是根据相片下载链接添加了下载任务而已，下载后的结果助手决定不了，助手只是个脚本性的扩展而已，如果是应用程序还好说。

有个python版的脚本你可以试试。好像有回写exif的功能。

**Comment by cqboyone** [comment]
感谢🙏
