### ISSUE TITLE
可不可以考虑一下限制查看大图时候图片底下的文字数量

### ISSUE THREAD

**Issue by STDquantum** [ShunCai/QZoneExport#77]
当文字比较长的时候图片会被挤得很小。

## 说说截图

这里倒是没有什么问题

![image](https://user-images.githubusercontent.com/60764289/155295782-a15d3537-2e9b-4cdc-ad2d-037a3e4c3785.png)

## 点开大图

完全被覆盖住了

![image](https://user-images.githubusercontent.com/60764289/155295858-14f25ea9-f4a3-498f-8490-40d4a365da89.png)

## 点那个放大按钮

什么也没有，全黑了

![image](https://user-images.githubusercontent.com/60764289/155295928-af444cf6-ee54-4906-ba11-03b4c6d58947.png)

**Comment by STDquantum** [comment]
我自己的解决办法是直接不显示说说内容，但可能有些极端。

麻烦您了😅

**Comment by ShunCai** [comment]
这个可以，当初没考虑到长说说了。

**Comment by ShunCai** [comment]
你这是在做测试吗 😂

**Comment by STDquantum** [comment]
并不是，只是自己说说里遇到了问题，把这个问题在小号上表现得夸张点😂
