### ISSUE TITLE
可不可以考虑一下把当前备份信息一块放到备份文件夹里

### ISSUE THREAD

**Issue by STDquantum** [ShunCai/QZoneExport#78]
我不太清楚这东西的实现难度所以只是提个建议😂

我是把它当成一个实时同步的工具用的，可能和原先设计需求不同。

## 可能的实现方式

把浏览器里的信息存成json或者什么的形式，启动的时候读取或者上传这个文件。

## 能解决掉的一些可能不方便的点

- 切换 QQ 号时之前 QQ 号的信息没了（增量备份读不到之前的信息），当几个 QQ 都需要增量备份就没办法实现。换几个浏览器实在有点麻烦。
- 万一手残清掉缓存还有补救余地。
- 可以比较方便地修改一些信息。
    - 比如全量备份后进行了一个说说的修改，然后自定义到那个位置。之后要再想用增量的话，上次备份时间就变成了自定义备份进行的那个时间，备份下来的效果是 之前的自定义部分都不会被读取。
    - 如果自己修改能解决掉上次备份时间这个问题。也就避免了进行两次自定义备份（第二次是当前时间）才能正确使用增量备份。

**Comment by ShunCai** [comment]
> 把浏览器里的信息存成json或者什么的形式，启动的时候读取或者上传这个文件。

这个本来就在计划中了，只是优先级不是很高，一般人来说，备份一次就完事了，而且，其实全量备份也不麻烦，所以增量备份的东西基本都排在后面，因为我基本都是全量备份的，增量备份这功能之前实现后，就没再用过，也不知道现在有没有问题。

> 切换 QQ 号时之前 QQ 号的信息没了（增量备份读不到之前的信息），当几个 QQ 都需要增量备份就没办法实现。换几个浏览器实在有点麻烦。

这个印象中，是支持切换账号的，当初的设计，备份的内容时跟QQ号走的，只是不太确定行不行，增量备份似乎在某些情况不起作用，还没仔细分析。

> 比如全量备份后进行了一个说说的修改，然后自定义到那个位置。之后要再想用增量的话，上次备份时间就变成了自定义备份进行的那个时间，备份下来的效果是 之前的自定义部分都不会被读取。
如果自己修改能解决掉上次备份时间这个问题。也就避免了进行两次自定义备份（第二次是当前时间）才能正确使用增量备份。

没怎么看明白问题，不过是支持自定义时间，然后再自定义时间后的内容都会增量合并的，不过正如上面所说，增量备份似乎在某些情况不起作用，昨晚我就尝试自定义时间想指备份昨天的说说，发现居然没起作用，不知道是测试的QQ号说说条目少还是别的原因，还待分析中。。。。

**Comment by STDquantum** [comment]
emmm主要是我这两千多条说说所以全量比较麻烦，大概要半个小时以上才能好，所以如果缓存搞坏了极其麻烦。

确实您说的问题我能理解，具体时间看您的安排。

**Comment by ShunCai** [comment]
晚上睡觉前扔在那让它备份，第二天起来就完事了 😂
