### ISSUE TITLE
考虑保存备份【好友对自己开放的相片】？

### ISSUE THREAD

**Issue by hailang8635** [ShunCai/QZoneExport#79]

**Comment by ShunCai** [comment]
什么意思，不是本来就有这个功能么

**Comment by hailang8635** [comment]
> 

就是把自己有权限访问的照片都download下来？
比如我能访问我A同学、B朋友、C亲戚的空间照片，加个自动遍历A、B、C空间照片的功能？自己有权限访问的情况下

**Comment by ShunCai** [comment]
助手是单个号备份的，没有批量备份多个号的功能，需要的话，你自己每个号进去备份。
