### ISSUE TITLE
希望增加旧版样式好友列表的切换功能

### ISSUE THREAD

**Issue by Tsubamei** [ShunCai/QZoneExport#80]
新版的好友列表不如之前的简洁直观，也不带搜索框，
希望能在设置里选择切换新版还是旧版样式

**Comment by ShunCai** [comment]
> 新版的好友列表不如之前的简洁直观，也不带搜索框，
> 希望能在设置里选择切换新版还是旧版样式

有开关啊，自己换回去就行，好友>展示方式

**Comment by Tsubamei** [comment]
好的 感谢
