### ISSUE TITLE
获取单页的说说列表异常

### ISSUE THREAD

**Issue by Tsubamei** [ShunCai/QZoneExport#86]
助手显示：
已采集说说模块数据，已完成
已获取第 1 页的说说列表，已获取 0 条，已失败 0 条，总共 0 条，已完成
（实际空间有3000+条说说；日志采集正常）

控制台报错信息如下：
![Snipaste_2022-11-11_12-04-45](https://user-images.githubusercontent.com/61179776/201260837-aca68fb3-f4fa-4110-8f4c-2971ca9c2aa8.png)

**Comment by ShunCai** [comment]
自己看下QQ空间的说说能不能正常出来

**Comment by Tsubamei** [comment]
（操作前路由器重新拨号、清除系统DNS缓存、清空浏览器缓存，排除网络问题）
问题过程复现
1.使用的是助手默认设置，打开了展开全文功能
2.登录空间后开始备份，助手提示开始获取说说
3.在“获取到51页，已获取1020条”后，此时控制台报错如下图，但是助手提示里的页数还在增加，获取条数维持1020，已失败维持0条。
![Snipaste_2022-11-19_16-11-01](https://user-images.githubusercontent.com/61179776/202841499-0430402e-afb8-4371-af6c-3d5b848df413.png)
4.最终结果：
已获取第 187 页的说说列表，已获取 1100 条，已失败 0 条，总共 3726 条，已完成
5.打包下载后关闭助手，在空间主页一直向下拉，可以正常显示说说

**Comment by ShunCai** [comment]
这个十有八九是QQ空间限制了，怀疑是空间最近更新了限制，目前有几个人反馈都是这个原因，目前没辙，比如返回使用人数过多，请稍后重试之类的

**Comment by Tsubamei** [comment]
Object里确实有 message: "使用人数过多，请稍后再试"
我把请求每页条目数改成40后，能获取到1600+条了

**Comment by ShunCai** [comment]
只能只能多获取一点数据，还是获取不全，而且，有些人，调整到40一页是直接获取不到的。

**Comment by Tsubamei** [comment]
有个抖音点赞视频下载工具，能实现关闭浏览器后，再次打开时继续上次下载的功能
https://chrome.google.com/webstore/detail/ldllbcnpihgljdgpjgdopgeejenhnabf

我想能不能在返回“使用人数过多”后，结束本次说说下载，继续下载日志和其他内容
等到下次使用时，对比之前的记录，从中断处继续下载，直到全部下载完成

**Comment by ShunCai** [comment]
可以是可以，但是麻烦，很多场景都得考虑到，而且，助手不再更新了。

**Comment by Tsubamei** [comment]
我把查询间隔改成61-62秒，每页条数20条后全部导出成功了，
只是时间有点长，用了三个多小时

**Comment by ShunCai** [comment]
那也行，起码导出来了
