### ISSUE TITLE
M3U8视频无法下载

### ISSUE THREAD

**Issue by CalunVier** [ShunCai/QZoneExport#87]
看起来插件似乎不能下载M3U8链接的视频。
我是用Mortix作为下载器，并且正确配置
当我尝试备份时，所有m3u8链接的视频均被下载为1kb的损坏文件

**Comment by ShunCai** [comment]
空间可以传M3U8？如果可以，那确实肯定不行，那跟普通视频不是一回事

**Comment by ShunCai** [comment]
> > 空间可以传M3U8？如果可以，那确实肯定不行，那跟普通视频不是一回事
> 
> emmmmmmm，或许是上传上去之后腾讯转码成了m3u8？我不是很确定具体的机制，但是我确实是遇到了m3u8的视频。

我印象中是不行的，是不是从微视同步的？

**Comment by CalunVier** [comment]
> > > 空间可以传M3U8？如果可以，那确实肯定不行，那跟普通视频不是一回事
> > 
> > 
> > emmmmmmm，或许是上传上去之后腾讯转码成了m3u8？我不是很确定具体的机制，但是我确实是遇到了m3u8的视频。
> 
> 我印象中是不行的，是不是从微视同步的？

我不知道为什么那个视频为什么是m3u8。但是或许可以请求支持一下m3u8的解析？应该有现成的库可以调用

**Comment by ShunCai** [comment]
不更新了
