### ISSUE TITLE
请问能否加入自定义备份范围/备份顺序or被拒绝请求后自动暂停等待网络恢复的功能

### ISSUE THREAD

**Issue by Abukuma316** [ShunCai/QZoneExport#89]
可能是最近跨年服务器压力大， 也有可能是请求的比较多，最近会出现抓取几千条以后就会卡“使用人数过多，请稍后再试”，然后服务器会拒绝访问请求，导致备份只能抓取到最新的四千多条。

而增量备份和自定义备份的逻辑，都是抓取某时间以前的“最新”内容，没办法在之前的基础上备份没有抓取到的旧内容，就很难整。

所以有没有可能，给自定义加上可选备份时间的首尾范围，或添加逆序/顺序备份选项。
抑或是增加一个发现抓取数量和嗅探到的总量or返回“使用人数过多，请稍后再试”时自动暂停半小时再继续抓取的功能（？）

本人编程小白，只能根据体验从直觉上给一些想法，如果无法实现或者想的过于简单还请大佬见谅！

祝生活愉快！

_Originally posted by @Abukuma316 in https://github.com/ShunCai/QZoneExport/discussions/88_

**Comment by ShunCai** [comment]
可以，复杂，麻烦，懒得搞，而且过段时间就把项目归档了，1.8是最后一个版本了。

至于使用人数过多的问题，哪怕你自己在页面上连续不停的翻页也会提示这个，空间的限制，可以自己调整一下采集间隔时间就好了，比如10-30，20-30，20-50，30-50，30-60等等，可参考置顶问题#86
