### ISSUE TITLE
mac 导出的文件在哪个目录

### ISSUE THREAD

**Issue by lovecn** [ShunCai/QZoneExport#9]
如题

**Comment by ShunCai** [comment]
不用Mac，理论上是自己选择保存位置的，如果没有提示保存位置，看看是不是浏览器设置了默认保存位置。

**Comment by ShunCai** [comment]
> 如题

没用过Mac，不过，理论上是自己选择保存位置的，如果没有提示保存位置，看看是不是浏览器设置了默认保存位置。比如，Chrome设置里关闭了【下载前询问每个文件的保存位置】，在关闭的情况下，Chrome会默认保存到你设置的下载文件夹。

**Comment by work4blue** [comment]
mac 下载显示100%，但是未显示查看备份，这个压缩文件是一个zip还是一个目录？

**Comment by ShunCai** [comment]
压缩文件肯定是ZIP呀，楼主贫穷用不起Mac，自己找找吧，如果没提示保存位置，一般在浏览器设置的下载目录。

**Comment by work4blue** [comment]
![image](https://user-images.githubusercontent.com/1583762/74359753-d04d9a00-4dfe-11ea-9281-f5aa7a752121.png)
一直100%，正在下载，也没有在下载目录找到任何东西

**Comment by ShunCai** [comment]
这种情况应该是打包报错了，你可以看看控制台，下次优化下给个提示吧。
打包报错的原因应该是文件过大，8千多个图片，建议使用迅雷或浏览器下载方式下载。

**Comment by work4blue** [comment]
重新下载，上一次作废了？这个应该简单计算一下，自动换成相应工具比较好，

**Comment by ShunCai** [comment]
对，每次都是重新下载的，没有做增量下载。

可以获取相册容量大概计算大小，然后做个提示，让用户更换下载工具。

不能自动切换工具的，浏览器和迅雷的下载方式是有限制的，例如没安装迅雷呢？浏览器没关闭【下载前询问每个文件的保存位置】呢？最终还是个坑。
