### ISSUE TITLE
备份后图片格式变成文件，无法直接打开。

### ISSUE THREAD

**Issue by agoodfriend** [ShunCai/QZoneExport#91]

**Comment by ShunCai** [comment]
哪个模块，具体提问题，就一句话谁知道呢，有图有真相

**Comment by agoodfriend** [comment]
老师，您好。。我不太会上传图片 这  \Messages\images  下载的文件。需要添加后缀 jpeg 才能直接显示。

**Comment by agoodfriend** [comment]
[](url)
![QQ图片20230206171028](https://user-images.githubusercontent.com/31264391/216931273-e783e621-6e10-4921-9a03-1c6b9cd600a4.png)

**Comment by ShunCai** [comment]
公共配置，把图片类型识别打开

**Comment by agoodfriend** [comment]
谢谢大师！！！
