### ISSUE TITLE
手机访问或者浏览器宽度过窄时，index.html中，footer标签会挡住最下面的足迹按钮

### ISSUE THREAD

**Issue by STDquantum** [ShunCai/QZoneExport#92]
参考解决办法：
把common.css里.header的position和top属性去掉，再加一个#index_html设置margin
![image](https://user-images.githubusercontent.com/60764289/217251110-34d9b885-a30f-4a3c-b941-37e286c4a311.png)

**Comment by ShunCai** [comment]
都改好了就直接提个PR呗

**Comment by ShunCai** [comment]
一般也没啥问题，移动端看足迹也不友好
