### ISSUE TITLE
无论增量与否，friends都会把所有好友的互动信息什么的爬一遍

### ISSUE THREAD

**Issue by STDquantum** [ShunCai/QZoneExport#94]
我看了看您的代码，发现在跳过爬过的好友时，API.Friends.isNewItem似乎没有起作用，之前已经有的好友仍然返回是true。

这个函数里面先判断是不是增量备份这里没什么问题，但是似乎return时候，这个||应该换成&&。

因为friends这个item进入getFriendsTime等三个函数的时候，传参是Qzone.Friends.Data，而这个Data在先前是被清空过的。那么之前打的不是newitem的标记被清掉了，API.Common.isNewItem返回会是true，按照函数的逻辑或直接就返回true了。

但是真正要判断又只能是通过OLD_Data的getIndex来搞，所以应当这两个同时为true的时候才能判断是新加入的item。

改掉后实测旧好友不会再爬一遍了。

----

另外之前您说提交pr的事，我现在还不太会，等我研究研究弄一下。😂

**Comment by ShunCai** [comment]
我瞧瞧，我一块改了。

**Comment by ShunCai** [comment]
按道理，OLD_Data的getIndex，就能判断出来了。不需要两个同时为true。
